# Generated by Django 5.0.7 on 2024-09-09 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='show_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
