# Generated by Django 5.0.7 on 2024-09-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_show_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='show_yn',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
