# Generated by Django 5.0.7 on 2024-09-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reply_deleted_at_reply_show_yn'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sort',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
