# Generated by Django 5.0.7 on 2024-08-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_path',
            field=models.FileField(upload_to='images/'),
        ),
    ]
