# Generated by Django 5.0.7 on 2024-09-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='show_yn',
            field=models.BooleanField(default=True),
        ),
    ]
