# Generated by Django 5.0.7 on 2024-09-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sogsag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=100)),
                ('status', models.IntegerField(default=0)),
                ('type', models.IntegerField(default=0)),
                ('ref_id', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
