# Generated by Django 5.0.7 on 2024-08-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monster',
            old_name='description',
            new_name='desc',
        ),
    ]
