# Generated by Django 5.0.7 on 2024-08-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isg', '0003_sogsag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('reward', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='sogsag',
            old_name='datetime',
            new_name='reg_date',
        ),
        migrations.AddField(
            model_name='sogsag',
            name='ref_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sogsag',
            name='status',
            field=models.CharField(default='R', max_length=1),
        ),
    ]
