# Generated by Django 5.0.7 on 2024-08-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isg', '0004_quest_rename_datetime_sogsag_reg_date_sogsag_ref_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sogsag',
            name='type',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sogsag',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
