# Generated by Django 5.0.7 on 2024-08-13 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isg', '0005_sogsag_type_alter_sogsag_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('uploaded_file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
