# Generated by Django 5.0.7 on 2024-08-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isg', '0006_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
