# Generated by Django 5.0.7 on 2024-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_sampledoc_uploadfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='idx',
            field=models.IntegerField(default=0),
        ),
    ]
