# Generated by Django 5.0.7 on 2024-08-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_uploadfile_original_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='original_file_name',
            field=models.TextField(),
        ),
    ]
